name: pptx_parsing
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  archive: ^4.0.9
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  http: ^1.6.0
  xml: ^7.0.1
  provider: ^6.1.2
  path_provider: ^2.1.4
  file_saver: ^0.4.0
  permission_handler: ^12.0.1
  share_plus: ^12.0.2
  file_picker: ^11.0.2
  arcore_flutter_plus:
    path: modified/arcore_flutter_plus-1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/test.pptx